"""initial migration

Revision ID: 043456a0eb42
Revises: 
Create Date: 2024-03-31 21:09:31.212252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043456a0eb42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bird_feeder',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'food_id')
    )
    op.create_table('discard_cards',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('deck_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_card_id'], ['deck_card.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'deck_card_id')
    )
    op.create_table('game_deck',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('deck_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_card_id'], ['deck_card.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'deck_card_id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('deck_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_card_id'], ['deck_card.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'deck_card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hand')
    op.drop_table('player')
    op.drop_table('game_deck')
    op.drop_table('discard_cards')
    op.drop_table('bird_feeder')
    op.drop_table('user')
    op.drop_table('game')
    op.drop_table('food')
    op.drop_table('deck_card')
    # ### end Alembic commands ###
