"""added user_id to Player

Revision ID: 25db6eaf32df
Revises: 043456a0eb42
Create Date: 2024-03-31 21:18:53.279550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25db6eaf32df'
down_revision = '043456a0eb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
