"""relationships in segment settings

Revision ID: 52131051ac40
Revises: 1d3a005b4548
Create Date: 2024-05-06 16:37:44.119964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52131051ac40'
down_revision = '1d3a005b4548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_settings_join',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_setting.id'], ),
    sa.ForeignKeyConstraint(['settings_id'], ['segment_settings.id'], ),
    sa.PrimaryKeyConstraint('model_id', 'settings_id')
    )
    op.create_table('segment_settings_segment_join',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['conversation_segment.id'], ),
    sa.ForeignKeyConstraint(['settings_id'], ['segment_settings.id'], ),
    sa.PrimaryKeyConstraint('segment_id', 'settings_id')
    )
    with op.batch_alter_table('segment_settings', schema=None) as batch_op:
        batch_op.drop_constraint('segment_settings_segment_id_fkey', type_='foreignkey')
        batch_op.drop_column('segment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('segment_settings_segment_id_fkey', 'conversation_segment', ['segment_id'], ['id'])

    op.drop_table('segment_settings_segment_join')
    op.drop_table('model_settings_join')
    # ### end Alembic commands ###
