"""update

Revision ID: 95b7f475019d
Revises: 968d6f30f063
Create Date: 2024-05-13 09:12:13.602363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b7f475019d'
down_revision = '968d6f30f063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment_settings_segment_join')
    with op.batch_alter_table('segment_settings', schema=None) as batch_op:
        batch_op.drop_constraint('segment_settings_segment_id_fkey', type_='foreignkey')
        batch_op.drop_column('segment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('segment_settings_segment_id_fkey', 'conversation_segment', ['segment_id'], ['id'])

    op.create_table('segment_settings_segment_join',
    sa.Column('segment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('settings_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['conversation_segment.id'], name='segment_settings_segment_join_segment_id_fkey'),
    sa.ForeignKeyConstraint(['settings_id'], ['segment_settings.id'], name='segment_settings_segment_join_settings_id_fkey'),
    sa.PrimaryKeyConstraint('segment_id', 'settings_id', name='segment_settings_segment_join_pkey')
    )
    # ### end Alembic commands ###
