"""updated relationship segment and settings

Revision ID: 968d6f30f063
Revises: 423ad603faac
Create Date: 2024-05-07 10:24:40.262691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968d6f30f063'
down_revision = '423ad603faac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'conversation_segment', ['segment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('segment_id')

    # ### end Alembic commands ###
